const { Schema, model } = require('mongoose');

const allProductsSchema = new Schema({
    img: {type: String, required: true},
    title: {type: String, required: true},
    discountedPrice: {type: String, required: true},
    originalPrice: {type: String, required: true},
    offPercentage: {type: String, required: true},
    ratings: {type: String, required: true},
    reviews: {type: String, required: true},
    saveRupees: {type: String, required: true},

    shadeOneTitle: {type: String, required: true},
    shadeOne: {type: String, required: true},
    shadeTwoTitle: {type: String, required: true},
    shadeTwo: {type: String, required: true},
    shadeThreeTitle: {type: String, required: true},
    shadeThree: {type: String, required: true},
    shadeFourTitle: {type: String, required: true},
    shadeFour: {type: String, required: true},
    shadeFiveTitle: {type: String, required: true},
    shadeFive: {type: String, required: true},
    shadeSixTitle: {type: String, required: true},
    shadeSix: {type: String, required: true},
    shadeSevenTitle: {type: String, required: true},
    shadeSeven: {type: String, required: true},
    shadeEightTitle: {type: String, required: true},
    shadeEight: {type: String, required: true},
    shadeNineTitle: {type: String, required: true},
    shadeNine: {type: String, required: true},
    shadeTenTitle: {type: String, required: true},
    shadeTen: {type: String, required: true},
    shadeElevenTitle: {type: String, required: true},
    shadeEleven: {type: String, required: true},
    shadeTwelveTitle: {type: String, required: true},
    shadeTwelve: {type: String, required: true},
    shadeThirteenTitle: {type: String, required: true},
    shadeThirteen: {type: String, required: true},
    shadeFourteenTitle: {type: String, required: true},
    shadeFourteen: {type: String, required: true},
    shadeFifteenTitle: {type: String, required: true},
    shadeFifteen: {type: String, required: true},

    shades_available: {type: String, required: true},

    imageOne: {type: String, required: true},
    imageTwo: {type: String, required: true},
    imageThree: {type: String, required: true},
    imageFour: {type: String, required: true},
    imageFive: {type: String, required: true},

    zoomImageOne: {type: String, required: true},
    zoomImageTwo: {type: String, required: true},
    zoomImageThree: {type: String, required: true},
    zoomImageFour: {type: String, required: true},
    zoomImageFive: {type: String, required: true},

    highlights: {type: String, required: true},

    benefitsImageOne: {type: String, required: true},
    benefitsImageTwo: {type: String, required: true},
    benefitsImageThree: {type: String, required: true},
    benefitsImageFour: {type: String, required: true},
    benefitsImageFive: {type: String, required: true},

    description: {type: String, required: true},

    speciality: {type: String, required: true},
    MakeupColorFamily: {type: String, required: true},
    Finish: {type: String, required: true},
    LastingPower: {type: String, required: true},
    ProductFormat: {type: String, required: true},
    Range: {type: String, required: true},
    Coverage: {type: String, required: true},
    Benefits: {type: String, required: true},
    ProductType: {type: String, required: true},
    CountryOfOrigin: {type: String, required: true},
    
    ingredients: {type: String, required: true},
    aboutBrand: {type: String, required: true},

    ftmImage: {type: String, required: true},
    tagLine: {type: String, required: true},
    benefitsImage: {type: String, required: true},
    howToUseImage: {type: String, required: true},
    shadeOneImage: {type: String, required: true},
    shadeTwoImage: {type: String, required: true},
    shadeThreeImage: {type: String, required: true},
    shadeFourImage: {type: String, required: true},
    shadeFiveImage: {type: String, required: true},
    shadeSixImage: {type: String, required: true},
    shadeSevenImage: {type: String, required: true},
    shadeEightImage: {type: String, required: true},
    shadeNineImage: {type: String, required: true},
    shadeTenImage: {type: String, required: true},
    shadeElevenImage: {type: String, required: true},
    shadeTwelveImage: {type: String, required: true},
    shadeThirteenImage: {type: String, required: true},
    shadeFourteenImage: {type: String, required: true},
    shadeFifteenImage: {type: String, required: true},
    tryItOutImage: {type: String, required: true},
    
    reviewsUserImageOne: {type: String, required: true},
    reviewsUserNameOne: {type: String, required: true},
    reviewsTitleOne: {type: String, required: true},
    reviewsRatingOne: {type: String, required: true},
    reviewsContentOne: {type: String, required: true},
    reviewsPostedTimeOne: {type: String, required: true},

    reviewsUserImageTwo: {type: String, required: true},
    reviewsUserNameTwo: {type: String, required: true},
    reviewsTitleTwo: {type: String, required: true},
    reviewsRatingTwo: {type: String, required: true},
    reviewsContentTwo: {type: String, required: true},
    reviewsPostedTimeTwo: {type: String, required: true},

    reviewsUserImageThree: {type: String, required: true},
    reviewsUserNameThree: {type: String, required: true},
    reviewsTitleThree: {type: String, required: true},
    reviewsRatingThree: {type: String, required: true},
    reviewsContentThree: {type: String, required: true},
    reviewsPostedTimeThree: {type: String, required: true},
}, 
{
    versionKey: false,
    timestamps: true
});

const Allproduct = model('allproduct', allProductsSchema);

module.exports = Allproduct;

